name: Build and Publish Caddy Docker Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v1.0.0)'
        required: false
        default: 'latest'

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO || 'sztuxp/caddy' }}
  REGISTRY: docker.io

jobs:
  build-binaries:
    name: Build Caddy Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os: linux
            arch: amd64
            docker_arch: amd64
          - os: linux
            arch: arm64
            docker_arch: arm64
          - os: linux
            arch: arm
            arm: 7
            docker_arch: arm
          - os: linux
            arch: 386
            docker_arch: 386

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Install cross-compilation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

      - name: Set binary name
        run: |
          if [ "${{ matrix.platform.arm }}" != "" ]; then
            echo "BINARY_NAME=caddy-linux-${{ matrix.platform.arch }}v${{ matrix.platform.arm }}" >> $GITHUB_ENV
          else
            echo "BINARY_NAME=caddy-linux-${{ matrix.platform.arch }}" >> $GITHUB_ENV
          fi

      - name: Build Caddy for ${{ matrix.platform.arch }}
        run: |
          export GOOS=${{ matrix.platform.os }}
          export GOARCH=${{ matrix.platform.arch }}
          if [ "${{ matrix.platform.arm }}" != "" ]; then
            export GOARM=${{ matrix.platform.arm }}
          fi
          
          go mod tidy
          CGO_ENABLED=0 go build -a -ldflags '-extldflags "-static"' -o $BINARY_NAME .
          ls -la $BINARY_NAME

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: caddy-${{ matrix.platform.os }}-${{ matrix.platform.arch }}${{ matrix.platform.arm != '' && format('v{0}', matrix.platform.arm) || '' }}
          path: caddy-linux-${{ matrix.platform.arch }}${{ matrix.platform.arm != '' && format('v{0}', matrix.platform.arm) || '' }}
          if-no-files-found: error

  build-docker-images:
    name: Build Docker Images
    needs: build-binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - os: linux
            arch: amd64
            docker_arch: amd64
          - os: linux
            arch: arm64
            docker_arch: arm64
          - os: linux
            arch: arm
            arm: 7
            docker_arch: arm
          - os: linux
            arch: 386
            docker_arch: 386

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: caddy-${{ matrix.platform.os }}-${{ matrix.platform.arch }}${{ matrix.platform.arm != '' && format('v{0}', matrix.platform.arm) || '' }}

      - name: Rename binary
        run: |
          mv caddy-linux-${{ matrix.platform.arch }}${{ matrix.platform.arm != '' && format('v{0}', matrix.platform.arm) || '' }} caddy
          chmod +x caddy
          ls -la caddy

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM alpine:latest
          RUN apk --no-cache add ca-certificates tzdata
          WORKDIR /root/
          COPY caddy /usr/bin/caddy
          RUN chmod +x /usr/bin/caddy
          RUN adduser -D -H -u 1001 caddy
          USER caddy
          EXPOSE 80 443 2019
          ENTRYPOINT ["/usr/bin/caddy"]
          CMD ["run", "--config", "/etc/caddy/Caddyfile"]
          EOF

      - name: Get version tag
        run: |
          if [ "${{ github.event.inputs.version }}" != "latest" ]; then
            echo "VERSION_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image for ${{ matrix.platform.docker_arch }}
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/${{ matrix.platform.docker_arch }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:${{ matrix.platform.docker_arch }}
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:${{ matrix.platform.docker_arch }}-${{ env.VERSION_TAG }}

  create-manifest:
    name: Create Multi-arch Manifest
    needs: build-docker-images
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version tag
        run: |
          if [ "${{ github.event.inputs.version }}" != "latest" ]; then
            echo "VERSION_TAG=${{ github.event.inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Create and push manifest
        run: |
          # Create manifest for latest tag
          docker buildx imagetools create \
            --tag ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:${{ env.VERSION_TAG }} \
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:amd64 \
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:arm64 \
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:arm \
            ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:386

          # If version is not latest, also tag as latest
          if [ "${{ env.VERSION_TAG }}" != "latest" ]; then
            docker buildx imagetools create \
              --tag ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:latest \
              ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:amd64 \
              ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:arm64 \
              ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:arm \
              ${{ env.REGISTRY }}/${{ env.DOCKERHUB_REPO }}:386
          fi
