name: Publish Caddy Docker Image

# 允许手动触发工作流
on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Download AMD64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: caddy-binaries-linux-amd64
          path: ./artifacts/caddy-binaries-linux-amd64

      - name: Download ARM64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: caddy-binaries-linux-arm64
          path: ./artifacts/caddy-binaries-linux-arm64

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/caddy-custom:latest
